version: "3.8"
services:
  nginx:
    restart: unless-stopped
    image: nginx:latest
    container_name: nginx
    ports:
      - 5050:5050
    volumes:
      - ./projects:/projects
      - ./nginx/sites:/etc/nginx/conf.d
    networks:
      - backend

networks:
  backend:
    driver: 'bridge'